/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.miempresa.views;

import com.miempresa.db.dbUserDAO;
import com.miempresa.librarysystem.Librarysystem;
import com.miempresa.model.User;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author FullFontJ
 */
public class FormNuevoUsuario extends javax.swing.JPanel {
    private boolean formEditUser = false;
    private int editUser;
    /**
     * Creates new form FormNuevoUsuario
     */
    public FormNuevoUsuario() {
        initComponents();
        initStyle();
    }
    
    public FormNuevoUsuario(int idUser) {
        editUser = idUser;
        formEditUser = true;
        initComponents();
        initStyle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldNameUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAddNewUser = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR NUEVO USUARIO");

        jLabel2.setText("Nombre Completo");

        btnAddNewUser.setBackground(new java.awt.Color(141, 73, 37));
        btnAddNewUser.setFont(new java.awt.Font("Segoe UI SemiLight", 1, 13)); // NOI18N
        btnAddNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewUser.setText("AGREGAR USUARIO");
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnAddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed
        User usuario = new User();
        usuario.setName(TextFieldNameUser.getText());

        
       try {
           dbUserDAO DBUsuario = new dbUserDAO();

           if(formEditUser){
               usuario.setId(editUser);
               DBUsuario.modificar(usuario);
               JOptionPane.showMessageDialog(null, "Nuevos cambios registrados.", "Actualizar Usuario", JOptionPane.INFORMATION_MESSAGE);
           }else{ 
               DBUsuario.registrar(usuario);
               JOptionPane.showMessageDialog(null, "Nuevo usuario registrado.", "Registro de Usuario", JOptionPane.INFORMATION_MESSAGE);
           }
            Librarysystem.changePanel(new ViewUsuario());

       } catch (HeadlessException e) {
           System.out.println("Error");
           JOptionPane.showMessageDialog(null, "Compruebas que los datos ingresado sean corretos.", "Usuario", JOptionPane.ERROR_MESSAGE);
       }  
        
    }//GEN-LAST:event_btnAddNewUserActionPerformed

    private void initStyle(){
        jLabel1.putClientProperty( "FlatLaf.styleClass", "h1" );
        TextFieldNameUser.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario");
    
        if(formEditUser){
            dbUserDAO getUsuario = new dbUserDAO();
            User usuariById  = getUsuario.getUserById(editUser);
            
            TextFieldNameUser.setText(usuariById.getName());
            jLabel1.setText("EDITAR USUARIO");
            btnAddNewUser.setText("GUARDAR CAMBIOS");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldNameUser;
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
