/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.miempresa.views;

import com.miempresa.db.dbPrestamoDAO;
import com.miempresa.librarysystem.Librarysystem;
import com.miempresa.model.Prestamo;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FullFontJ
 */
public class ViewPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form Prestamo
     */
    public ViewPrestamo() {
        initComponents();
        initStyle();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddPrestamo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePrestamo = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(649, 455));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRETAMOS");

        btnAddPrestamo.setBackground(new java.awt.Color(141, 73, 37));
        btnAddPrestamo.setFont(new java.awt.Font("Segoe UI SemiLight", 1, 13)); // NOI18N
        btnAddPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPrestamo.setText("REGISTRAR PRESTAMO");
        btnAddPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrestamoActionPerformed(evt);
            }
        });

        TablePrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Libro", "Usuario", "Fecha Prestamo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablePrestamo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddPrestamo)
                .addGap(25, 25, 25))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrestamoActionPerformed
         Librarysystem.changePanel(new FormNuevoPrestamo());
    }//GEN-LAST:event_btnAddPrestamoActionPerformed
    
    private void initStyle(){
        jLabel1.putClientProperty( "FlatLaf.styleClass", "h1" );
    }
    
    private void loadData(){
        try {
            dbPrestamoDAO pretamoDB = new dbPrestamoDAO();
            List<Prestamo> listaPrestamo = pretamoDB.listar();
            DefaultTableModel model = (DefaultTableModel) TablePrestamo.getModel();
            for(Prestamo prestamo : listaPrestamo){
                model.addRow(new Object[]{prestamo.getId(), prestamo.getTituloLibro(), prestamo.getNombreUsuario(), prestamo.getFechaPrestamo()});
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePrestamo;
    private javax.swing.JButton btnAddPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
