/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.miempresa.views;

import com.miempresa.db.dbPrestamoDAO;
import com.miempresa.model.Prestamo;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author FullFontJ
 */
public class ViewDevolucion extends javax.swing.JPanel {

    /**
     * Creates new form Devolucion
     */
    public ViewDevolucion() {
        initComponents();
        initStyle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldLibro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldUsuario = new javax.swing.JTextField();
        btnDevolucion = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEVOLUCIONES");

        jLabel2.setText("Numero De Serie Del Libro");

        jLabel3.setText("ID De Usuario");

        btnDevolucion.setBackground(new java.awt.Color(141, 73, 37));
        btnDevolucion.setFont(new java.awt.Font("Segoe UI SemiLight", 1, 13)); // NOI18N
        btnDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolucion.setText("PROCESAR DEVOLUCIÓN");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        int serieLibro = Integer.parseInt(TextFieldLibro.getText());
        int idUsuario = Integer.parseInt(TextFieldUsuario.getText());
        Prestamo devolucionPrestamo = new Prestamo();
        devolucionPrestamo.setIdBook(serieLibro);
        devolucionPrestamo.setIdUser(idUsuario);
        
        try {
            dbPrestamoDAO dbPrestamo = new dbPrestamoDAO();
            dbPrestamo.modificar(devolucionPrestamo);
            JOptionPane.showMessageDialog(null, "Nueva devolución realizada", "Devolución", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Compruebas que los datos ingresado sean corretos.", "Devolución", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void initStyle(){
        jLabel1.putClientProperty( "FlatLaf.styleClass", "h1" );
        jLabel2.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabel3.putClientProperty( "FlatLaf.styleClass", "h3" ); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldLibro;
    private javax.swing.JTextField TextFieldUsuario;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
